### ISSUE TITLE
Robot moves at max speed all the time

### ISSUE THREAD

**Issue by samohtj** [powerstackers/FTC-5029-Velocity-Vortex#9]
Our movement code is set up in a way that makes the robot move at maximum speed all the time. In `setMovement()`, we determine the highest motor setting and then divide all the motor settings by that number, meaning that one of the motor settings is always 1.0. This shouldn't be the case. We should scale all the motor settings, and then multiply them all by the speed parameter. Or better yet, don't scale them at all unless one of them is greater than 1, and then it will scale them _back_ and not forward.

**Comment by tcychu** [comment]
This is Justin.  The current code already normalises the speed if largest > 1.0.  If not, then the speed will be < 1.0.  There is a scale variable that will decrease power to motors by 0.0 to 1.0  The scale can be set in VelTeleop and activated if driver _taps_ on A.  Default scale is 1.0

**Comment by krish-suresh** [comment]
This is fixed
